---
- hosts: digitalocean

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"

  tasks:

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file=.ssh/id_rsa

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=desk-ubuntu
      ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
      api_token={{ do_token }}
    register: desk_ubuntu

  - name: ensure droplet one exists
    digital_ocean: >
      state=absent
      command=droplet
      name=droplet-one
      unique_name=yes
      size_id=s-1vcpu-1gb
      region_id=fra1
      image_id=debian-9-x64
      ssh_key_ids={{ desk_ubuntu.ssh_key.id }}
      api_token={{ do_token }}
    register: droplet_one

  - debug: msg="IP is {{ droplet_one.droplet.ip_address }}"
